// Import necessary Angular modules and libraries
import { Component, OnInit } from '@angular/core';  // Core Angular decorators and lifecycle hook
import { CommonModule } from '@angular/common';      // Common Angular directives like *ngIf, *ngFor
import { FormsModule } from '@angular/forms';        // Two-way data binding with [(ngModel)]
import { HttpClient } from '@angular/common/http';   // For making API calls to backend
import * as XLSX from 'xlsx';                        // Library for exporting data to Excel files

// Interface: Defines the structure of a Budget object
// This ensures type safety - we know exactly what properties a budget should have
interface Budget {
  id?: number;                    // Optional: Auto-generated by database when budget is saved
  name: string;                   // Budget name (e.g., "2026 Operating Budget")
  description: string;            // Detailed description of the budget
  fiscalYear: number;             // Year this budget applies to (e.g., 2026)
  period: string;                 // MONTHLY, QUARTERLY, or ANNUALLY
  type: string;                   // OPERATING, CAPITAL, CASH_FLOW, or MASTER
  status: string;                 // DRAFT, SUBMITTED, APPROVED, ACTIVE, or CLOSED
  startDate: string;              // When budget period starts (YYYY-MM-DD format)
  endDate: string;                // When budget period ends
  createdDate?: string;           // Optional: When budget was created
  approvedDate?: string;          // Optional: When budget was approved
  approvedBy?: string;            // Optional: Who approved the budget
  notes: string;                  // Additional comments or notes
  budgetLines?: BudgetLine[];     // Optional: Array of line items in the budget
}

// Interface: Represents one line item in a budget
// Example: "Salaries Account - $50,000 budgeted for Q1"
interface BudgetLine {
  id?: number;            // Optional: Auto-generated ID
  accountId: number;      // Which account this budget line is for (e.g., Salaries, Rent)
  amount: number;         // Dollar amount budgeted for this account
  notes: string;          // Additional notes about this budget line
  lineType?: string;      // Optional: REVENUE or EXPENSE
}

// Interface: Represents a financial account from Chart of Accounts
// Used in dropdowns so user can select which account to budget for
interface Account {
  id: number;       // Unique identifier
  code: string;     // Account code (e.g., "1000", "4000")
  name: string;     // Account name (e.g., "Cash", "Sales Revenue")
  type: string;     // ASSET, LIABILITY, EQUITY, REVENUE, or EXPENSE
  status: string;   // ACTIVE or INACTIVE
}

// Interface: Variance Analysis compares budgeted amounts vs actual amounts
// This shows how well the company is sticking to its budget
interface VarianceAnalysis {
  budgetId: number;       // Which budget we're analyzing
  budgetName: string;     // Name of the budget
  period: string;         // Time period being analyzed
  startDate: string;      // Start of analysis period
  endDate: string;        // End of analysis period
  lines: any[];           // Detailed line-by-line comparison
  summary: {              // Overall summary of variances
    totalBudgetRevenue: number;     // How much revenue was budgeted
    totalActualRevenue: number;     // How much revenue actually came in
    revenueVariance: number;        // Difference (positive = better than expected)
    totalBudgetExpense: number;     // How much expense was budgeted
    totalActualExpense: number;     // How much was actually spent
    expenseVariance: number;        // Difference (negative = spent less than budgeted)
    budgetNetIncome: number;        // Expected profit (Revenue - Expense)
    actualNetIncome: number;        // Actual profit
    netIncomeVariance: number;      // How much better/worse than expected
  };
}

@Component({
  selector: 'app-budget',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="budget-container">
      <div class="header">
        <h2>Budget Management</h2>
        <div class="header-actions">
          <button class="btn-primary" (click)="openBudgetModal()" *ngIf="canEdit">
            <i class="icon">📊</i> Create Budget
          </button>
          <button class="btn-secondary" (click)="exportBudgets()">
            <i class="icon">📥</i> Export
          </button>
        </div>
      </div>

      <!-- Summary Cards -->
      <div class="summary-cards">
        <div class="card">
          <div class="card-header">Active Budgets</div>
          <div class="card-value">{{ activeBudgetsCount }}</div>
        </div>
        <div class="card">
          <div class="card-header">Total Budgeted Revenue</div>
          <div class="card-value">{{ totalBudgetedRevenue | number:'1.2-2' }}</div>
        </div>
        <div class="card">
          <div class="card-header">Total Budgeted Expense</div>
          <div class="card-value">{{ totalBudgetedExpense | number:'1.2-2' }}</div>
        </div>
        <div class="card">
          <div class="card-header">Budgets Pending Approval</div>
          <div class="card-value">{{ pendingApprovalsCount }}</div>
        </div>
      </div>

      <!-- Filters -->
      <div class="filters">
        <input type="text" [(ngModel)]="searchTerm" (input)="applyFilters()" 
               placeholder="Search by name..." class="search-input">
        
        <select [(ngModel)]="filterYear" (change)="applyFilters()" class="filter-select">
          <option value="">All Years</option>
          <option *ngFor="let year of availableYears" [value]="year">{{ year }}</option>
        </select>

        <select [(ngModel)]="filterStatus" (change)="applyFilters()" class="filter-select">
          <option value="">All Statuses</option>
          <option value="DRAFT">Draft</option>
          <option value="SUBMITTED">Submitted</option>
          <option value="APPROVED">Approved</option>
          <option value="ACTIVE">Active</option>
          <option value="CLOSED">Closed</option>
        </select>

        <select [(ngModel)]="filterType" (change)="applyFilters()" class="filter-select">
          <option value="">All Types</option>
          <option value="OPERATING">Operating</option>
          <option value="CAPITAL">Capital</option>
          <option value="CASH_FLOW">Cash Flow</option>
          <option value="MASTER">Master</option>
        </select>
      </div>

      <!-- Budget List -->
      <div class="table-container">
        <table class="data-table">
          <thead>
            <tr>
              <th>Budget Name</th>
              <th>Type</th>
              <th>Fiscal Year</th>
              <th>Period</th>
              <th>Start Date</th>
              <th>End Date</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let budget of filteredBudgets">
              <td>{{ budget.name }}</td>
              <td>{{ budget.type }}</td>
              <td>{{ budget.fiscalYear }}</td>
              <td>{{ budget.period }}</td>
              <td>{{ budget.startDate | date:'MM/dd/yyyy' }}</td>
              <td>{{ budget.endDate | date:'MM/dd/yyyy' }}</td>
              <td>
                <span class="status-badge" [class.status-draft]="budget.status === 'DRAFT'"
                      [class.status-submitted]="budget.status === 'SUBMITTED'"
                      [class.status-approved]="budget.status === 'APPROVED'"
                      [class.status-active]="budget.status === 'ACTIVE'"
                      [class.status-closed]="budget.status === 'CLOSED'">
                  {{ budget.status }}
                </span>
              </td>
              <td class="actions-cell">
                <button class="btn-icon" (click)="viewBudgetDetails(budget)" title="View Details">👁️</button>
                <button class="btn-icon" (click)="viewVarianceAnalysis(budget)" title="Variance Analysis" 
                        *ngIf="budget.status === 'ACTIVE' || budget.status === 'APPROVED'">📊</button>
                <button class="btn-icon" (click)="editBudget(budget)" title="Edit" 
                        *ngIf="canEdit && (budget.status === 'DRAFT' || budget.status === 'SUBMITTED')">✏️</button>
                <button class="btn-icon" (click)="submitBudget(budget)" title="Submit for Approval" 
                        *ngIf="canEdit && budget.status === 'DRAFT'">📤</button>
                <button class="btn-icon" (click)="approveBudget(budget)" title="Approve" 
                        *ngIf="canEdit && budget.status === 'SUBMITTED'">✅</button>
                <button class="btn-icon" (click)="activateBudget(budget)" title="Activate" 
                        *ngIf="canEdit && budget.status === 'APPROVED'">▶️</button>
                <button class="btn-icon btn-danger" (click)="deleteBudget(budget)" title="Delete" 
                        *ngIf="canEdit && budget.status === 'DRAFT'">🗑️</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Budget Modal -->
      <div class="modal" *ngIf="showBudgetModal" (click)="closeBudgetModal($event)">
        <div class="modal-content" (click)="$event.stopPropagation()">
          <div class="modal-header">
            <h3>{{ isEditMode ? 'Edit Budget' : 'Create New Budget' }}</h3>
            <button class="close-btn" (click)="closeBudgetModal($event)">&times;</button>
          </div>
          <div class="modal-body">
            <form (ngSubmit)="saveBudget()">
              <div class="form-row">
                <div class="form-group">
                  <label>Budget Name *</label>
                  <input type="text" [(ngModel)]="currentBudget.name" name="name" required>
                </div>
                <div class="form-group">
                  <label>Fiscal Year *</label>
                  <input type="number" [(ngModel)]="currentBudget.fiscalYear" name="fiscalYear" required>
                </div>
              </div>

              <div class="form-row">
                <div class="form-group">
                  <label>Budget Type *</label>
                  <select [(ngModel)]="currentBudget.type" name="type" required>
                    <option value="OPERATING">Operating</option>
                    <option value="CAPITAL">Capital</option>
                    <option value="CASH_FLOW">Cash Flow</option>
                    <option value="MASTER">Master</option>
                  </select>
                </div>
                <div class="form-group">
                  <label>Period *</label>
                  <select [(ngModel)]="currentBudget.period" name="period" required>
                    <option value="MONTHLY">Monthly</option>
                    <option value="QUARTERLY">Quarterly</option>
                    <option value="ANNUALLY">Annually</option>
                  </select>
                </div>
              </div>

              <div class="form-row">
                <div class="form-group">
                  <label>Start Date *</label>
                  <input type="date" [(ngModel)]="currentBudget.startDate" name="startDate" required>
                </div>
                <div class="form-group">
                  <label>End Date *</label>
                  <input type="date" [(ngModel)]="currentBudget.endDate" name="endDate" required>
                </div>
              </div>

              <div class="form-group">
                <label>Description</label>
                <textarea [(ngModel)]="currentBudget.description" name="description" rows="3"></textarea>
              </div>

              <div class="form-group">
                <label>Notes</label>
                <textarea [(ngModel)]="currentBudget.notes" name="notes" rows="2"></textarea>
              </div>

              <!-- Budget Lines Section -->
              <div class="budget-lines-section">
                <div class="section-header">
                  <h4>Budget Line Items</h4>
                  <button type="button" class="btn-small" (click)="addBudgetLine()">+ Add Line</button>
                </div>
                
                <div class="budget-lines-table" *ngIf="currentBudget.budgetLines && currentBudget.budgetLines.length > 0">
                  <table class="mini-table">
                    <thead>
                      <tr>
                        <th>Account</th>
                        <th>Amount</th>
                        <th>Notes</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr *ngFor="let line of currentBudget.budgetLines; let i = index">
                        <td>
                          <select [(ngModel)]="line.accountId" [name]="'accountId' + i" required>
                            <option [ngValue]="null">Select Account</option>
                            <option *ngFor="let account of accounts" [ngValue]="account.id">
                              {{ account.code }} - {{ account.name }}
                            </option>
                          </select>
                        </td>
                        <td>
                          <input type="number" [(ngModel)]="line.amount" [name]="'amount' + i" 
                                 step="0.01" min="0" required>
                        </td>
                        <td>
                          <input type="text" [(ngModel)]="line.notes" [name]="'notes' + i">
                        </td>
                        <td>
                          <button type="button" class="btn-icon btn-danger" (click)="removeBudgetLine(i)">🗑️</button>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn-secondary" (click)="closeBudgetModal($event)">Cancel</button>
                <button type="submit" class="btn-primary">Save Budget</button>
              </div>
            </form>
          </div>
        </div>
      </div>

      <!-- Variance Analysis Modal -->
      <div class="modal" *ngIf="showVarianceModal" (click)="closeVarianceModal($event)">
        <div class="modal-content modal-large" (click)="$event.stopPropagation()">
          <div class="modal-header">
            <h3>Variance Analysis - {{ varianceAnalysis?.budgetName }}</h3>
            <button class="close-btn" (click)="closeVarianceModal($event)">&times;</button>
          </div>
          <div class="modal-body" *ngIf="varianceAnalysis">
            <div class="variance-summary">
              <div class="variance-card">
                <h4>Revenue</h4>
                <div class="variance-row">
                  <span>Budget:</span>
                  <span>{{ varianceAnalysis.summary.totalBudgetRevenue | number:'1.2-2' }}</span>
                </div>
                <div class="variance-row">
                  <span>Actual:</span>
                  <span>{{ varianceAnalysis.summary.totalActualRevenue | number:'1.2-2' }}</span>
                </div>
                <div class="variance-row variance-total">
                  <span>Variance:</span>
                  <span [class.favorable]="varianceAnalysis.summary.revenueVariance >= 0"
                        [class.unfavorable]="varianceAnalysis.summary.revenueVariance < 0">
                    {{ varianceAnalysis.summary.revenueVariance | number:'1.2-2' }}
                  </span>
                </div>
              </div>

              <div class="variance-card">
                <h4>Expense</h4>
                <div class="variance-row">
                  <span>Budget:</span>
                  <span>{{ varianceAnalysis.summary.totalBudgetExpense | number:'1.2-2' }}</span>
                </div>
                <div class="variance-row">
                  <span>Actual:</span>
                  <span>{{ varianceAnalysis.summary.totalActualExpense | number:'1.2-2' }}</span>
                </div>
                <div class="variance-row variance-total">
                  <span>Variance:</span>
                  <span [class.favorable]="varianceAnalysis.summary.expenseVariance <= 0"
                        [class.unfavorable]="varianceAnalysis.summary.expenseVariance > 0">
                    {{ varianceAnalysis.summary.expenseVariance | number:'1.2-2' }}
                  </span>
                </div>
              </div>

              <div class="variance-card">
                <h4>Net Income</h4>
                <div class="variance-row">
                  <span>Budget:</span>
                  <span>{{ varianceAnalysis.summary.budgetNetIncome | number:'1.2-2' }}</span>
                </div>
                <div class="variance-row">
                  <span>Actual:</span>
                  <span>{{ varianceAnalysis.summary.actualNetIncome | number:'1.2-2' }}</span>
                </div>
                <div class="variance-row variance-total">
                  <span>Variance:</span>
                  <span [class.favorable]="varianceAnalysis.summary.netIncomeVariance >= 0"
                        [class.unfavorable]="varianceAnalysis.summary.netIncomeVariance < 0">
                    {{ varianceAnalysis.summary.netIncomeVariance | number:'1.2-2' }}
                  </span>
                </div>
              </div>
            </div>

            <h4 class="section-title">Line Item Details</h4>
            <div class="table-container">
              <table class="data-table">
                <thead>
                  <tr>
                    <th>Account</th>
                    <th>Type</th>
                    <th>Budget</th>
                    <th>Actual</th>
                    <th>Variance</th>
                    <th>Variance %</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <tr *ngFor="let line of varianceAnalysis.lines">
                    <td>{{ line.accountCode }} - {{ line.accountName }}</td>
                    <td>{{ line.lineType }}</td>
                    <td>{{ line.budgetAmount | number:'1.2-2' }}</td>
                    <td>{{ line.actualAmount | number:'1.2-2' }}</td>
                    <td [class.favorable]="line.status === 'FAVORABLE'"
                        [class.unfavorable]="line.status === 'UNFAVORABLE'">
                      {{ line.variance | number:'1.2-2' }}
                    </td>
                    <td>{{ line.variancePercent | number:'1.2-2' }}%</td>
                    <td>
                      <span class="variance-badge" 
                            [class.badge-favorable]="line.status === 'FAVORABLE'"
                            [class.badge-unfavorable]="line.status === 'UNFAVORABLE'"
                            [class.badge-target]="line.status === 'ON_TARGET'">
                        {{ line.status }}
                      </span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .budget-container { padding: 20px; }
    .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
    .header h2 { margin: 0; color: #2c3e50; }
    .header-actions { display: flex; gap: 10px; }
    
    .summary-cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 20px; }
    .card { background: white; padding: 15px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .card-header { font-size: 12px; color: #7f8c8d; margin-bottom: 8px; }
    .card-value { font-size: 24px; font-weight: bold; color: #2c3e50; }
    
    .filters { display: flex; gap: 10px; margin-bottom: 20px; flex-wrap: wrap; }
    .search-input, .filter-select { padding: 8px 12px; border: 1px solid #ddd; border-radius: 4px; }
    .search-input { flex: 1; min-width: 200px; }
    .filter-select { min-width: 150px; }
    
    .table-container { background: white; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); overflow-x: auto; }
    .data-table { width: 100%; border-collapse: collapse; }
    .data-table th, .data-table td { padding: 12px; text-align: left; border-bottom: 1px solid #ecf0f1; }
    .data-table th { background: #34495e; color: white; font-weight: 600; }
    .data-table tr:hover { background: #f8f9fa; }
    
    .status-badge { padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
    .status-draft { background: #95a5a6; color: white; }
    .status-submitted { background: #3498db; color: white; }
    .status-approved { background: #2ecc71; color: white; }
    .status-active { background: #27ae60; color: white; }
    .status-closed { background: #7f8c8d; color: white; }
    
    .actions-cell { display: flex; gap: 5px; }
    .btn-icon { background: none; border: none; font-size: 18px; cursor: pointer; padding: 4px; }
    .btn-icon:hover { transform: scale(1.2); }
    .btn-icon.btn-danger:hover { color: #e74c3c; }
    
    .btn-primary, .btn-secondary, .btn-small { padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; font-weight: 600; }
    .btn-primary { background: #3498db; color: white; }
    .btn-primary:hover { background: #2980b9; }
    .btn-secondary { background: #95a5a6; color: white; }
    .btn-secondary:hover { background: #7f8c8d; }
    .btn-small { padding: 6px 12px; font-size: 14px; background: #16a085; color: white; }
    
    .modal { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.5); display: flex; align-items: center; justify-content: center; z-index: 1000; }
    .modal-content { background: white; border-radius: 8px; width: 90%; max-width: 800px; max-height: 90vh; overflow-y: auto; }
    .modal-large { max-width: 1200px; }
    .modal-header { display: flex; justify-content: space-between; align-items: center; padding: 20px; border-bottom: 1px solid #ecf0f1; }
    .modal-header h3 { margin: 0; }
    .close-btn { background: none; border: none; font-size: 28px; cursor: pointer; color: #95a5a6; }
    .modal-body { padding: 20px; }
    .modal-footer { display: flex; justify-content: flex-end; gap: 10px; padding: 20px; border-top: 1px solid #ecf0f1; }
    
    .form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 15px; }
    .form-group { display: flex; flex-direction: column; }
    .form-group label { margin-bottom: 5px; font-weight: 600; color: #2c3e50; }
    .form-group input, .form-group select, .form-group textarea { padding: 8px; border: 1px solid #ddd; border-radius: 4px; }
    
    .budget-lines-section { margin-top: 20px; padding: 15px; background: #f8f9fa; border-radius: 4px; }
    .section-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px; }
    .section-header h4 { margin: 0; }
    
    .mini-table { width: 100%; border-collapse: collapse; }
    .mini-table th, .mini-table td { padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }
    .mini-table th { background: #ecf0f1; font-weight: 600; }
    .mini-table input, .mini-table select { width: 100%; padding: 6px; border: 1px solid #ddd; border-radius: 4px; }
    
    .variance-summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px; margin-bottom: 20px; }
    .variance-card { background: #f8f9fa; padding: 15px; border-radius: 8px; }
    .variance-card h4 { margin: 0 0 15px 0; color: #2c3e50; }
    .variance-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #ecf0f1; }
    .variance-row.variance-total { font-weight: bold; border-top: 2px solid #34495e; border-bottom: none; margin-top: 5px; }
    
    .favorable { color: #27ae60; font-weight: 600; }
    .unfavorable { color: #e74c3c; font-weight: 600; }
    
    .variance-badge { padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
    .badge-favorable { background: #d5f4e6; color: #27ae60; }
    .badge-unfavorable { background: #fadbd8; color: #e74c3c; }
    .badge-target { background: #d6eaf8; color: #2980b9; }
    
    .section-title { margin: 20px 0 10px 0; color: #2c3e50; }
    .icon { margin-right: 5px; }
  `]
})
// Main component class for Budget Management
export class BudgetComponent implements OnInit {
  // === DATA STORAGE ===
  budgets: Budget[] = [];            // All budgets from database
  filteredBudgets: Budget[] = [];    // Budgets after applying search/filters
  accounts: Account[] = [];          // All active accounts for dropdowns
  
  // === MODAL VISIBILITY FLAGS ===
  showBudgetModal = false;      // Show/hide the create/edit budget modal
  showVarianceModal = false;    // Show/hide the variance analysis modal
  isEditMode = false;           // True when editing existing budget, false when creating new
  
  // === CURRENT WORKING DATA ===
  currentBudget: Budget = this.getEmptyBudget();     // The budget being created/edited
  varianceAnalysis: VarianceAnalysis | null = null;  // Variance analysis results
  
  // === FILTER VARIABLES ===
  searchTerm = '';      // User's search text
  filterYear = '';      // Selected fiscal year filter
  filterStatus = '';    // Selected status filter (DRAFT, ACTIVE, etc.)
  filterType = '';      // Selected type filter (OPERATING, CAPITAL, etc.)
  
  // === SUMMARY STATISTICS ===
  availableYears: number[] = [];    // Years to show in dropdown (current year ± some years)
  activeBudgetsCount = 0;           // How many budgets are currently active
  pendingApprovalsCount = 0;        // How many budgets need approval
  totalBudgetedRevenue = 0;         // Sum of all budgeted revenue
  totalBudgetedExpense = 0;         // Sum of all budgeted expenses
  
  // === PERMISSIONS ===
  canEdit = false;      // Whether current user can create/edit budgets
  
  // === CONFIGURATION ===
  private apiUrl = 'http://localhost:8080/api';  // Backend API base URL
  
  // Constructor: Angular injects HttpClient so we can make API calls
  constructor(private http: HttpClient) {}
  
  // ngOnInit: Runs once when component loads
  // This is where we initialize data and load from backend
  ngOnInit() {
    this.checkUserRole();           // Check if user has edit permission
    this.loadBudgets();             // Load all budgets from backend
    this.loadAccounts();            // Load all accounts for dropdowns
    this.generateAvailableYears();  // Generate year options for filter
  }
  
  // Check if current user has permission to create/edit budgets
  // Role 0 = System Admin (full access)
  // Role 1 = Accountant (can edit)
  // Role 2 = Account Executive (read-only)
  checkUserRole() {
    const userIndex = sessionStorage.getItem('currentUserIndex');
    // System Admin (index 0) and Accountant (index 1) can edit, Account Executive (index 2) is read-only
    this.canEdit = userIndex === '0' || userIndex === '1';
  }
  
  // Generate a list of years for the year filter dropdown
  // Shows 2 years in the past up to 5 years in the future
  // Example: If current year is 2026, shows 2024, 2025, 2026...2031
  generateAvailableYears() {
    const currentYear = new Date().getFullYear();
    for (let i = currentYear - 2; i <= currentYear + 5; i++) {
      this.availableYears.push(i);
    }
  }
  
  // Load all budgets from the backend API
  // Makes HTTP GET request to /api/budgets
  // After loading, applies any active filters and calculates summary statistics
  loadBudgets() {
    this.http.get<Budget[]>(`${this.apiUrl}/budgets`).subscribe({
      next: (data) => {
        this.budgets = data;           // Store all budgets
        this.applyFilters();           // Filter based on current search/filter settings
        this.calculateSummary();       // Calculate counts and totals for cards
      },
      error: (error) => console.error('Error loading budgets:', error)
    });
  }
  
  // Load all active accounts from Chart of Accounts
  // Makes HTTP GET request to /api/accounts
  // Filters to show only ACTIVE accounts (ignore INACTIVE ones)
  // These accounts are used in dropdowns when creating budget lines
  loadAccounts() {
    this.http.get<Account[]>(`${this.apiUrl}/accounts`).subscribe({
      next: (data) => {
        this.accounts = data.filter(a => a.status === 'ACTIVE');  // Only show active accounts
      },
      error: (error) => console.error('Error loading accounts:', error)
    });
  }
  
  // Apply all active filters to the budget list
  // This function checks each budget against:
  // 1. Search term (searches in budget name)
  // 2. Year filter (matches fiscal year)
  // 3. Status filter (DRAFT, ACTIVE, etc.)
  // 4. Type filter (OPERATING, CAPITAL, etc.)
  // Only budgets that match ALL filters are shown
  applyFilters() {
    this.filteredBudgets = this.budgets.filter(budget => {
      const matchesSearch = budget.name.toLowerCase().includes(this.searchTerm.toLowerCase());
      const matchesYear = !this.filterYear || budget.fiscalYear.toString() === this.filterYear;
      const matchesStatus = !this.filterStatus || budget.status === this.filterStatus;
      const matchesType = !this.filterType || budget.type === this.filterType;
      
      return matchesSearch && matchesYear && matchesStatus && matchesType;
    });
  }
  
  // Calculate summary statistics shown in the cards at the top
  // - Count how many budgets are active
  // - Count how many budgets are waiting for approval (SUBMITTED status)
  // - Sum up total budgeted revenue and expenses (currently simplified)
  calculateSummary() {
    this.activeBudgetsCount = this.budgets.filter(b => b.status === 'ACTIVE').length;
    this.pendingApprovalsCount = this.budgets.filter(b => b.status === 'SUBMITTED').length;
    
    // Calculate totals (simplified - would need to fetch budget lines for accurate totals)
    this.totalBudgetedRevenue = 0;
    this.totalBudgetedExpense = 0;
  }
  
  // Open modal to create a NEW budget
  // Resets the form to empty values and sets edit mode to false
  openBudgetModal() {
    this.currentBudget = this.getEmptyBudget();  // Get a fresh empty budget object
    this.isEditMode = false;                     // We're creating, not editing
    this.showBudgetModal = true;                 // Show the modal
  }
  
  // Open modal to EDIT an existing budget
  // Makes a copy of the budget data and loads its line items from backend
  editBudget(budget: Budget) {
    this.currentBudget = { ...budget };  // Create a copy of budget (... is spread operator)
    this.isEditMode = true;              // We're editing, not creating
    this.showBudgetModal = true;         // Show the modal
    
    // Load budget lines from backend (separate API call)
    // This gets all the individual line items (account + amount pairs)
    this.http.get<BudgetLine[]>(`${this.apiUrl}/budgets/${budget.id}/lines`).subscribe({
      next: (lines) => {
        this.currentBudget.budgetLines = lines;  // Attach lines to budget object
      },
      error: (error) => console.error('Error loading budget lines:', error)
    });
  }
  
  // Save budget to backend (either create new or update existing)
  // This is called when user clicks "Save" button in the modal
  saveBudget() {
    // Filter out budget lines with null or invalid accountId
    // This prevents saving incomplete lines that user might have started but not finished
    const budgetToSave = { ...this.currentBudget };
    if (budgetToSave.budgetLines) {
      budgetToSave.budgetLines = budgetToSave.budgetLines.filter(line => 
        line.accountId != null && line.accountId > 0
      );
    }
    
    // Choose the right HTTP method based on edit mode:
    // - PUT (update) if editing existing budget
    // - POST (create) if creating new budget
    const request = this.isEditMode 
      ? this.http.put<Budget>(`${this.apiUrl}/budgets/${this.currentBudget.id}`, budgetToSave)
      : this.http.post<Budget>(`${this.apiUrl}/budgets`, budgetToSave);
    
    request.subscribe({
      next: () => {
        alert(`Budget ${this.isEditMode ? 'updated' : 'created'} successfully!`);
        this.loadBudgets();              // Reload the list to show changes
        this.showBudgetModal = false;    // Close the modal
      },
      error: (error) => {
        console.error('Error saving budget:', error);
        alert('Error saving budget. Please try again.');
      }
    });
  }
  
  // Delete a budget permanently from the database
  // NOTE: Only DRAFT budgets can be deleted (backend enforces this rule)
  // Approved or active budgets cannot be deleted for audit trail reasons
  deleteBudget(budget: Budget) {
    if (confirm(`Are you sure you want to delete budget "${budget.name}"?`)) {
      this.http.delete(`${this.apiUrl}/budgets/${budget.id}`).subscribe({
        next: () => {
          alert('Budget deleted successfully!');
          this.loadBudgets();  // Refresh the list
        },
        error: (error) => {
          console.error('Error deleting budget:', error);
          alert('Error deleting budget. Only draft budgets can be deleted.');
        }
      });
    }
  }
  
  // Submit budget for approval
  // Changes status from DRAFT → SUBMITTED
  // Budget must have at least one line item to be submitted
  submitBudget(budget: Budget) {
    this.http.post<Budget>(`${this.apiUrl}/budgets/${budget.id}/submit`, {}).subscribe({
      next: () => {
        alert('Budget submitted for approval!');
        this.loadBudgets();  // Reload to show new status
      },
      error: (error) => {
        console.error('Error submitting budget:', error);
        alert('Error submitting budget. Ensure budget has at least one line item.');
      }
    });
  }
  
  // Approve a budget
  // Changes status from SUBMITTED → APPROVED
  // Records who approved it and when
  approveBudget(budget: Budget) {
    const approver = prompt('Enter approver name:');  // Ask for approver's name
    if (approver) {
      this.http.post<Budget>(`${this.apiUrl}/budgets/${budget.id}/approve`, { approvedBy: approver }).subscribe({
        next: () => {
          alert('Budget approved!');
          this.loadBudgets();  // Reload to show new status
        },
        error: (error) => {
          console.error('Error approving budget:', error);
          alert('Error approving budget.');
        }
      });
    }
  }
  
  // Activate a budget
  // Changes status from APPROVED → ACTIVE
  // Active budgets are the ones currently being used for tracking
  activateBudget(budget: Budget) {
    this.http.post<Budget>(`${this.apiUrl}/budgets/${budget.id}/activate`, {}).subscribe({
      next: () => {
        alert('Budget activated!');
        this.loadBudgets();  // Reload to show new status
      },
      error: (error) => {
        console.error('Error activating budget:', error);
        alert('Error activating budget.');
      }
    });
  }
  
  viewBudgetDetails(budget: Budget) {
    this.editBudget(budget);
  }
  
  viewVarianceAnalysis(budget: Budget) {
    this.http.get<VarianceAnalysis>(`${this.apiUrl}/budgets/${budget.id}/variance-analysis`).subscribe({
      next: (analysis) => {
        this.varianceAnalysis = analysis;
        this.showVarianceModal = true;
      },
      error: (error) => {
        console.error('Error loading variance analysis:', error);
        alert('Error loading variance analysis.');
      }
    });
  }
  
  addBudgetLine() {
    if (!this.currentBudget.budgetLines) {
      this.currentBudget.budgetLines = [];
    }
    this.currentBudget.budgetLines.push({
      accountId: null as any,
      amount: 0,
      notes: ''
    });
  }
  
  removeBudgetLine(index: number) {
    this.currentBudget.budgetLines?.splice(index, 1);
  }
  
  closeBudgetModal(event: Event) {
    event.preventDefault();
    this.showBudgetModal = false;
  }
  
  closeVarianceModal(event: Event) {
    event.preventDefault();
    this.showVarianceModal = false;
  }
  
  exportBudgets() {
    if (!this.filteredBudgets || this.filteredBudgets.length === 0) {
      alert('No budgets to export. Please create budgets first.');
      return;
    }

    // Prepare budget summary data
    const budgetSummary = this.filteredBudgets.map(budget => ({
      'Budget Name': budget.name,
      'Fiscal Year': budget.fiscalYear,
      'Period': budget.period,
      'Type': budget.type,
      'Status': budget.status,
      'Start Date': budget.startDate,
      'End Date': budget.endDate,
      'Total Lines': budget.budgetLines?.length || 0,
      'Description': budget.description || ''
    }));

    // Create workbook
    const wb = XLSX.utils.book_new();

    // Add Budget Summary sheet
    const wsSummary = XLSX.utils.json_to_sheet(budgetSummary);
    wsSummary['!cols'] = [
      { wch: 25 }, { wch: 12 }, { wch: 12 }, { wch: 15 },
      { wch: 12 }, { wch: 12 }, { wch: 12 }, { wch: 12 }, { wch: 40 }
    ];
    XLSX.utils.book_append_sheet(wb, wsSummary, 'Budget Summary');

    // Add detailed budget lines for each budget
    this.filteredBudgets.forEach((budget, index) => {
      if (budget.budgetLines && budget.budgetLines.length > 0) {
        const budgetLines = budget.budgetLines.map(line => {
          const account = this.accounts.find(a => a.id === line.accountId);
          return {
            'Account ID': line.accountId,
            'Account': account ? `${account.code} - ${account.name}` : 'Unknown',
            'Line Type': line.lineType,
            'Amount': line.amount,
            'Notes': line.notes || ''
          };
        });

        const wsLines = XLSX.utils.json_to_sheet(budgetLines);
        wsLines['!cols'] = [{ wch: 12 }, { wch: 30 }, { wch: 15 }, { wch: 15 }, { wch: 40 }];
        
        // Limit sheet name to 31 characters (Excel limit)
        const sheetName = budget.name.substring(0, 28) + (index + 1);
        XLSX.utils.book_append_sheet(wb, wsLines, sheetName);
      }
    });

    // Generate filename with current date
    const date = new Date().toISOString().split('T')[0];
    const filename = `Budgets_${date}.xlsx`;

    // Save file
    XLSX.writeFile(wb, filename);
  }
  
  private getEmptyBudget(): Budget {
    const currentYear = new Date().getFullYear();
    return {
      name: '',
      description: '',
      fiscalYear: currentYear,
      period: 'ANNUALLY',
      type: 'OPERATING',
      status: 'DRAFT',
      startDate: `${currentYear}-01-01`,
      endDate: `${currentYear}-12-31`,
      notes: '',
      budgetLines: []
    };
  }
}
